(ns dailp-ingest-clj.aspectual-suffixes-fiddle
  (:require [old-client.core :refer [make-old-client]]
            [dailp-ingest-clj.aspectual-suffixes :refer :all]))

(defn get-fake-state
  []
  {:old-client (make-old-client),
  :created_pronominal_prefixes [],
  :warnings
  {:negative-PPP-omission-warnings
   (list "Omitting ingestion of NEG morpheme with first allomorph 'kee' glossed as 'NEG2'."
    "Omitting ingestion of NEG morpheme with first allomorph 'ka' glossed as 'NEG1'.")},
  :tags
  {:ppp-pre-consonantal
   {:id 462,
    :name "ppp-pre-consonantal",
    :description "Pre-consonantal prepronominal prefix",
    :datetime_modified "2019-02-27T19:12:43.018729"},
   :ingest-tag
   {:id 457,
    :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z",
    :description
    "The tag for the data ingest that occurred at 2019-02-27T19:12:42.832Z.",
    :datetime_modified "2019-02-27T19:12:42.869485"},
   :mod-pre-v
   {:id 470,
    :name "mod-pre-v",
    :description "Modal suffix allomorphs before the vowel /v/.",
    :datetime_modified "2019-02-27T19:12:43.254330"},
   :refl-pre-h-s
   {:id 467,
    :name "refl-pre-h-s",
    :description
    "Reflexive or middle prefix allomorphs before the segments /h/ or /s/.",
    :datetime_modified "2019-02-27T19:12:43.177580"},
   :pp-pre-vocalic
   {:id 458,
    :name "pp-pre-vocalic",
    :description "Pre-vocalic pronominal prefix",
    :datetime_modified "2019-02-27T19:12:42.899756"},
   :mod-pre-vocalic
   {:id 469,
    :name "mod-pre-vocalic",
    :description "Modal suffix allomorphs before vowels.",
    :datetime_modified "2019-02-27T19:12:43.222982"},
   :refl-pre-a
   {:id 466,
    :name "refl-pre-a",
    :description "Reflexive or middle prefix allomorphs before the vowel /a/.",
    :datetime_modified "2019-02-27T19:12:43.152290"},
   :cl-pre-consonantal
   {:id 471,
    :name "cl-pre-consonantal",
    :description "Clitic allomorphs before consonants.",
    :datetime_modified "2019-02-27T19:12:43.288555"},
   :pp-pre-consonantal
   {:id 459,
    :name "pp-pre-consonantal",
    :description "Pre-consonantal pronominal prefix",
    :datetime_modified "2019-02-27T19:12:42.935605"},
   :cl-pre-vocalic
   {:id 472,
    :name "cl-pre-vocalic",
    :description "Clitic allomorphs before vowels.",
    :datetime_modified "2019-02-27T19:12:43.315213"},
   :pp-pre-v
   {:id 460,
    :name "pp-pre-v",
    :description
    "Pre-v pronominal prefix. This tag marks the \"3SG.B\" allomorph \"uwa-\" of pre-consonantal \"uu-\" (and pre-vocalic \"uw-\"). It occurs before stem-initial /v-/, which is a schwa-like vowel in Cherokee.",
    :datetime_modified "2019-02-27T19:12:42.967391"},
   :cl-pre-v
   {:id 473,
    :name "cl-pre-v",
    :description "Clitic allomorphs before the vowel /v/.",
    :datetime_modified "2019-02-27T19:12:43.342916"},
   :refl-pre-vocalic
   {:id 465,
    :name "refl-pre-vocalic",
    :description "Reflexive or middle prefix allomorphs before vowels.",
    :datetime_modified "2019-02-27T19:12:43.113663"},
   :mod-pre-consonantal
   {:id 468,
    :name "mod-pre-consonantal",
    :description "Modal suffix allomorphs before consonants.",
    :datetime_modified "2019-02-27T19:12:43.199141"},
   :refl-pre-consonantal
   {:id 464,
    :name "refl-pre-consonantal",
    :description "Reflexive or middle prefix allomorphs before consonants.",
    :datetime_modified "2019-02-27T19:12:43.085260"},
   :ppp-elsewhere
   {:id 463,
    :name "ppp-elsewhere",
    :description
    "Elsewhere prepronominal prefix. Prepronominal prefix allomorphs marked with this tag (e.g., /too/) occur before the CISL1, CISL2, and ITER1 prepronominal prefixes.",
    :datetime_modified "2019-02-27T19:12:43.053899"},
   :ppp-pre-vocalic
   {:id 461,
    :name "ppp-pre-vocalic",
    :description "Pre-vocalic prepronominal prefix",
    :datetime_modified "2019-02-27T19:12:42.993611"}},
  :syntactic-categories
  {:V
   {:id 100,
    :name "V",
    :type "lexical",
    :description "Verbs",
    :datetime_modified "2019-02-27T19:12:45.119392"},
   :S
   {:id 101,
    :name "S",
    :type "sentential",
    :description "Sentences",
    :datetime_modified "2019-02-27T19:12:45.154577"},
   :PP
   {:id 102,
    :name "PP",
    :type "lexical",
    :description "Pronominal Prefixes",
    :datetime_modified "2019-02-27T19:12:45.186971"},
   :PPP
   {:id 103,
    :name "PPP",
    :type "lexical",
    :description "Prepronominal Prefixes",
    :datetime_modified "2019-02-27T19:12:45.211729"},
   :REFL
   {:id 104,
    :name "REFL",
    :type "lexical",
    :description "Category for reflexive (REFL) and middle (MID) prefixes",
    :datetime_modified "2019-02-27T19:12:45.235630"},
   :MOD
   {:id 105,
    :name "MOD",
    :type "lexical",
    :description "Category for modal (MOD) suffixes",
    :datetime_modified "2019-02-27T19:12:45.271520"},
   :CL
   {:id 106,
    :name "CL",
    :type "lexical",
    :description "Category for clitics (CL)",
    :datetime_modified "2019-02-27T19:12:45.301521"},
   :ASP
   {:id 107,
    :name "ASP",
    :type "lexical",
    :description "Category for aspectual (ASP) suffixes",
    :datetime_modified "2019-02-27T19:12:45.338127"}},
  :sources {},
  :orthographies
  {626
   {:name "taoc modified community",
    :orthography
    "a, e, i, o, u, v, á, é, í, ó, ú, v́, à, è, ì, ò, ù, v̀, ?, ?, ?, ?, ?, ?, a:, e:, i:, o:, u:, v:, á:, é:, í:, ó:, ú:, v́:, ǎ:, ě:, ǐ:, ǒ:, ǔ, v̌:, â:, ê:, î:, ô, û:, v̂:, à:, è:, ì:, ò:, ù:, v̀:, a̋:, e̋:, i̋:, ő:, ű:, v̋:, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.055061",
    :id 626},
   627
   {:name "cherokee narratives",
    :orthography
    "a̱, e̱, i̱, o̱, u̱, v̱, a̱³, e̱³, i̱³, o̱³, u̱³, v̱³, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, a, e, i, o, u, v, a³, e³, i³, o³, u³, v³, a²³, e²³, i²³, o²³, u²³, v²³, a³², e³², i³², o³², u³², v³², a¹, e¹, i¹, o¹, u¹, v¹, a⁴, e⁴, i⁴, o⁴, u⁴, v⁴, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.084523",
    :id 627},
   628
   {:name "cherokee tone project",
    :orthography
    "ā, ē,  ī, ō,  ū,  v̄, á, é, í, ó, ú, v́, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ā:, ē:,  ī:, ō:,  ū:,  v̄:, á:, é:, í:, ó:, ú:, v́:, ǎ:, ě:, ǐ:, ǒ:, ǔ, v̌:, â:, ê:, î:, ô, û:, v̂:, à:, è:, ì:, ò:, ù:, v̀:, a̋:, e̋:, i̋:, ő:, ű:, v̋:, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.112260",
    :id 628},
   629
   {:name "taoc",
    :orthography
    "a, e, i, o, u, v, á, é, í, ó, ú, v́, à, è, ì, ò, ù, v̀, a̋, e̋, i̋, ő, ű, v̋, aa, ee, ii, oo, uu, vv, áá, éé, íí, óó, úú, v́v́, aá, eé, ií, oó, uú, vv́, áa, ée, íi, óo, úu, v́v, àà, èè, ìì, òò, ùù, v̀v̀, aa̋, ee̋, ii̋, oő, uű, vv̋, V, t, th , k, kh , kw, kwh, c , ch, tl, tlh, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.144859",
    :id 629},
   630
   {:name "dailp",
    :orthography
    "a, e, i, o, u, v, á, é, í, ó, ú, v́, à, è, ì, ò, ù, v̀, a̋, e̋, i̋, ő, ű, v̋, aa, ee, ii, oo, uu, vv, áá, éé, íí, óó, úú, v́v́, aá, eé, ií, oó, uú, vv́, áa, ée, íi, óo, úu, v́v, àà, èè, ìì, òò, ùù, v̀v̀, aa̋, ee̋, ii̋, oő, uű, vv̋, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.166291",
    :id 630},
   631
   {:name "uchihara database",
    :orthography
    "a, e, i, o, u, v, a!, e!, i!, o!, u!, v!, a`, e`, i`, o`, u`, v`, a\" , e\" , i\" , o\" , u\" , v\" , a:, e:, i:, o:, u:, v:, a:!, e:!, i:!, o:!, u:!, v:!, a:*, e:*, i:*, o:*, u:*, v:*, a:^, e:^, i:^, o:^, u:^, v:^, a:`, e:`, i:`, o:`, u:`, v:`, a:\" , e:\" , i:\" , o:\" , u:\" , v:\" , V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ', l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.190551",
    :id 631},
   632
   {:name "feeling 1975",
    :orthography
    "ạ², ẹ², ị², ọ², ụ², ṿ², ạ³, ẹ³, ị³, ọ³, ụ³, ṿ³, ạ¹, ẹ¹, ị¹, ọ¹, ụ¹, ṿ¹, ạ⁴, ẹ⁴, ị⁴, ọ⁴, ụ⁴, ṿ⁴, a², e², i², o², u², v², a³, e³, i³, o³, u³, v³, a²³, e²³, i²³, o²³, u²³, v²³, a³², e³², i³², o³², u³², v³², a¹, e¹, i¹, o¹, u¹, v¹, a⁴, e⁴, i⁴, o⁴, u⁴, v⁴, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.230708",
    :id 632},
   633
   {:name "crg",
    :orthography
    "a, e, i, o, u, v, á, é, í, ó, ú, v́, à, è, ì, ò, ù, v̀, ?, ?, ?, ?, ?, ?, aa, ee, ii, oo, uu, vv, áa, ée, íi, óo, úu, v́v, aá, eé, ií, oó, uú, vv́, áà, éè, íì, óò, úù, v́v̀, aà, eè, iì, oò, uù, vv̀, áá, éé, íí, óó, úú, v́v́, V, d, t, g, k, gw, kw, j, ch, dl, tl, s, h, ʔ, l, y, w, m",
    :lowercase false,
    :initial_glottal_stops true,
    :datetime_modified "2019-02-27T19:12:41.256785",
    :id 633}},
  :ppp-forms
  {299
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[299 "IRR" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:47.631869",
    :comments
    "H3 specification: +H3. tonicity: -tonic. TAOC: 27-29, 182. TAOC tag: IRR. Compare CRG (106-109) morpheme /yi-/ glossed 'IRR' and named 'Irrealis Prepronominal Prefix'. Compare BMA 2008 (297-303) morpheme /yi-/ glossed 'IRR' and named 'Irrealis Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "IRR",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "y|IRR|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[299 "y" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "y",
    :id 299,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:47.631869",
    :UUID "791957b0-e723-49f2-9bc3-19b13be0b60c",
    :speaker nil,
    :transcription "y",
    :elicitor nil,
    :translations
    [{:id 330,
      :transcription "Irrealis Prepronominal Prefix",
      :grammaticality ""}]},
   298
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[298 "IRR" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:47.545239",
    :comments
    "H3 specification: +H3. tonicity: -tonic. TAOC: 27-29, 182. TAOC tag: IRR. Compare CRG (106-109) morpheme /yi-/ glossed 'IRR' and named 'Irrealis Prepronominal Prefix'. Compare BMA 2008 (297-303) morpheme /yi-/ glossed 'IRR' and named 'Irrealis Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "IRR",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "yi|IRR|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[298 "yi" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "yi",
    :id 298,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:47.545239",
    :UUID "c7ed6187-570f-4a7a-b95b-1aa61b572eef",
    :speaker nil,
    :transcription "yi",
    :elicitor nil,
    :translations
    [{:id 329,
      :transcription "Irrealis Prepronominal Prefix",
      :grammaticality ""}]},
   311
   {:date_elicited nil,
    :tags
    [{:id 463, :name "ppp-elsewhere"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[311 "DIST2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.913255",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(ii). Compare CRG (110-112, 123-125, 355-356) morpheme /di-/ glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /ti-/ (/ta-/) glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "c|DIST2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[311 "c" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "c",
    :id 311,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.913255",
    :UUID "586de69a-41c6-4b4a-a76a-033f77d75838",
    :speaker nil,
    :transcription "c",
    :elicitor nil,
    :translations
    [{:id 342,
      :transcription "Distributive 2 Prepronominal Prefix",
      :grammaticality ""}]},
   322
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[322 "REL" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.964557",
    :comments
    "H3 specification: -H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: REL. Compare CRG (279-282) morpheme /ji-/ glossed 'REL' and named 'Relativizer Prepronominal Prefix'. Compare BMA 2008 (304-305) morpheme /ji-/ glossed 'REL' and named 'Relativizer Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "REL",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "c|REL|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[322 "c" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "c",
    :id 322,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.964557",
    :UUID "c2918d10-f85a-4dd6-a036-14aae8eded38",
    :speaker nil,
    :transcription "c",
    :elicitor nil,
    :translations
    [{:id 353,
      :transcription "Relative Prepronominal Prefix",
      :grammaticality ""}]},
   300
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[300 "TRNSL" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:47.733177",
    :comments
    "H3 specification: +H3. tonicity: -tonic. TAOC: 27-29, 182. TAOC tag: TRNSL. Compare CRG (104-106) morpheme /wi-/ glossed 'TRN' and named 'Translocative Prepronominal Prefix'. Compare BMA 2008 (307-312) morpheme /wi-/ glossed 'TRN' and named 'Translocative Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "TRNSL",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "wi|TRNSL|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[300 "wi" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "wi",
    :id 300,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:47.733177",
    :UUID "87214796-c8bb-4cf7-b880-ce3b7f07d1ad",
    :speaker nil,
    :transcription "wi",
    :elicitor nil,
    :translations
    [{:id 331,
      :transcription "Translocative Prepronominal Prefix",
      :grammaticality ""}]},
   319
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[319 "ITER2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.686313",
    :comments
    "H3 specification: +H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: ITER. Compare CRG (295) morpheme /vv-/ glossed 'ITR2' and named 'Iterative 2 Prepronominal Prefix'. Compare BMA 2008 (335-336) morpheme /vv-/ glossed 'ITR2' and named 'Iterative 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ITER2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "vv|ITER2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[319 "vv" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "vv",
    :id 319,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.686313",
    :UUID "627fdb68-9d10-4477-ac67-1bcf1a1e4ed1",
    :speaker nil,
    :transcription "vv",
    :elicitor nil,
    :translations
    [{:id 350,
      :transcription "Iterative 2 Prepronominal Prefix",
      :grammaticality ""}]},
   307
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[307 "DIST1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.515890",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(i). Compare CRG (109-113, 140, 304-305) morpheme /dee-/ (/doo-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /tee-/ (/too-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "t|DIST1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[307 "t" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "t",
    :id 307,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.515890",
    :UUID "3ed37fa4-625c-4628-8ec5-c1adf813e090",
    :speaker nil,
    :transcription "t",
    :elicitor nil,
    :translations
    [{:id 338,
      :transcription "Distributive 1 Prepronominal Prefix",
      :grammaticality ""}]},
   309
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[309 "DIST2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.713706",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(ii). Compare CRG (110-112, 123-125, 355-356) morpheme /di-/ glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /ti-/ (/ta-/) glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ti|DIST2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[309 "ti" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ti",
    :id 309,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.713706",
    :UUID "2cd0a64a-7ce6-463e-9505-7d9920ea4c23",
    :speaker nil,
    :transcription "ti",
    :elicitor nil,
    :translations
    [{:id 340,
      :transcription "Distributive 2 Prepronominal Prefix",
      :grammaticality ""}]},
   305
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[305 "PART2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.311596",
    :comments
    "TAOC: 27-29, 182. TAOC tag: PART. Compare CRG (287-288) morpheme /-ii-/ (/-iy-/) glossed 'NI2' and named 'ni- 2 Prepronominal Prefix '. Compare BMA 2008 (318) morpheme /ii-/ glossed 'PRT2' and named 'Partitive 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "PART2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "iy|PART2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[305 "iy" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "iy",
    :id 305,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.311596",
    :UUID "cc638d7e-3547-4689-a201-4f515e38f864",
    :speaker nil,
    :transcription "iy",
    :elicitor nil,
    :translations
    [{:id 336,
      :transcription "Partitive 2 Prepronominal Prefix",
      :grammaticality ""}]},
   314
   {:date_elicited nil,
    :tags
    [{:id 463, :name "ppp-elsewhere"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[314 "CISL1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.204617",
    :comments
    "H3 specification: +H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: CISL. Compare CRG (288-291) morpheme /di-/ glossed 'TOW' and named 'Toward Prepronominal Prefix'. Compare CRG (292-293) morpheme /da-/ (/di-/) glossed 'MOT2' and named 'Motion Toward 2 Prepronominal Prefix'. Compare BMA 2008 (326-328) morpheme /ti-/ (/ta-/) glossed 'CIS' and named 'Cislocative Prepronominal Prefix '.",
    :elicitation_method nil,
    :morpheme_gloss "CISL1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "c|CISL1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[314 "c" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "c",
    :id 314,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.204617",
    :UUID "02d1eb43-c0cf-41ea-b775-04cfa00ed61d",
    :speaker nil,
    :transcription "c",
    :elicitor nil,
    :translations
    [{:id 345,
      :transcription "Cislocative 1 Prepronominal Prefix",
      :grammaticality ""}]},
   304
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[304 "PART2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.204487",
    :comments
    "TAOC: 27-29, 182. TAOC tag: PART. Compare CRG (287-288) morpheme /-ii-/ (/-iy-/) glossed 'NI2' and named 'ni- 2 Prepronominal Prefix '. Compare BMA 2008 (318) morpheme /ii-/ glossed 'PRT2' and named 'Partitive 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "PART2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ii|PART2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[304 "ii" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ii",
    :id 304,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.204487",
    :UUID "db6070af-9551-4350-aa87-e5004e5d52e7",
    :speaker nil,
    :transcription "ii",
    :elicitor nil,
    :translations
    [{:id 335,
      :transcription "Partitive 2 Prepronominal Prefix",
      :grammaticality ""}]},
   317
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[317 "ITER1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.521626",
    :comments
    "H3 specification: +H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: ITER. Compare CRG (293-296) morpheme /ii-/ (/hii-/) glossed 'ITR' and named 'Iterative Prepronominal Prefix'. Compare BMA 2008 (333-336) morpheme /ii-/ (/hii-/) glossed 'ITR' and named 'Iterative Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ITER1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ii|ITER1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[317 "ii" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ii",
    :id 317,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.521626",
    :UUID "0ed3bf68-28ce-406f-811f-7e0366c01e77",
    :speaker nil,
    :transcription "ii",
    :elicitor nil,
    :translations
    [{:id 348,
      :transcription "Iterative 1 Prepronominal Prefix",
      :grammaticality ""}]},
   308
   {:date_elicited nil,
    :tags
    [{:id 463, :name "ppp-elsewhere"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[308 "DIST1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.615937",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(i). Compare CRG (109-113, 140, 304-305) morpheme /dee-/ (/doo-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /tee-/ (/too-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "too|DIST1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[308 "too" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "too",
    :id 308,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.615937",
    :UUID "a66d60e0-e5c1-4012-8d58-4550fa7f79db",
    :speaker nil,
    :transcription "too",
    :elicitor nil,
    :translations
    [{:id 339,
      :transcription "Distributive 1 Prepronominal Prefix",
      :grammaticality ""}]},
   316
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[316 "CISL2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.434922",
    :comments
    "H3 specification: +H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: CISL. Compare CRG (289-290) morpheme /da-/ glossed 'TOW2' and named 'Toward 2 Prepronominal Prefix'. Compare CRG (291-293) morpheme /da-/ glossed 'MOT' and named 'Motion Toward Prepronominal Prefix'. Compare CRG (115-117) morpheme /da-/ glossed 'CMF' and named 'Completive Future Prepronominal Prefix '. Compare BMA 2008 (328-329) morpheme /ta-/ glossed 'CSM' and named 'Cislocative Motion Prepronominal Prefix '. Compare BMA 2008 (329-332) morpheme /ta-/ glossed 'FUT' and named 'Future ta- Prepronominal Prefix '.",
    :elicitation_method nil,
    :morpheme_gloss "CISL2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "tay|CISL2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[316 "tay" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "tay",
    :id 316,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.434922",
    :UUID "37af7b08-f3c2-41c8-a931-270d12039c56",
    :speaker nil,
    :transcription "tay",
    :elicitor nil,
    :translations
    [{:id 347,
      :transcription "Cislocative 2 Prepronominal Prefix",
      :grammaticality ""}]},
   303
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[303 "PART1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.072902",
    :comments
    "H3 specification: ±H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: PART. Compare CRG (283-288) morpheme /ni-/ glossed 'NI' and named 'ni- Prepronominal Prefix '. Compare BMA 2008 (312-317) morpheme /ni-/ glossed 'PRT' and named 'Partitive Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "PART1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "n|PART1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[303 "n" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "n",
    :id 303,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.072902",
    :UUID "460e782f-2608-4041-9be9-dd1def2ba7d5",
    :speaker nil,
    :transcription "n",
    :elicitor nil,
    :translations
    [{:id 334,
      :transcription "Partitive 1 Prepronominal Prefix",
      :grammaticality ""}]},
   310
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[310 "DIST2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.827556",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(ii). Compare CRG (110-112, 123-125, 355-356) morpheme /di-/ glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /ti-/ (/ta-/) glossed 'DST2' and named 'Distributive 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "t|DIST2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[310 "t" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "t",
    :id 310,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.827556",
    :UUID "3e363880-3736-4053-b36b-0ff5b6e1a9b0",
    :speaker nil,
    :transcription "t",
    :elicitor nil,
    :translations
    [{:id 341,
      :transcription "Distributive 2 Prepronominal Prefix",
      :grammaticality ""}]},
   313
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[313 "CISL1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.113719",
    :comments
    "H3 specification: +H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: CISL. Compare CRG (288-291) morpheme /di-/ glossed 'TOW' and named 'Toward Prepronominal Prefix'. Compare CRG (292-293) morpheme /da-/ (/di-/) glossed 'MOT2' and named 'Motion Toward 2 Prepronominal Prefix'. Compare BMA 2008 (326-328) morpheme /ti-/ (/ta-/) glossed 'CIS' and named 'Cislocative Prepronominal Prefix '.",
    :elicitation_method nil,
    :morpheme_gloss "CISL1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "t|CISL1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[313 "t" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "t",
    :id 313,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.113719",
    :UUID "3b44b5d9-e224-4cf0-92c0-516932b13fa0",
    :speaker nil,
    :transcription "t",
    :elicitor nil,
    :translations
    [{:id 344,
      :transcription "Cislocative 1 Prepronominal Prefix",
      :grammaticality ""}]},
   301
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[301 "TRNSL" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:47.837100",
    :comments
    "H3 specification: +H3. tonicity: -tonic. TAOC: 27-29, 182. TAOC tag: TRNSL. Compare CRG (104-106) morpheme /wi-/ glossed 'TRN' and named 'Translocative Prepronominal Prefix'. Compare BMA 2008 (307-312) morpheme /wi-/ glossed 'TRN' and named 'Translocative Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "TRNSL",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "w|TRNSL|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[301 "w" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "w",
    :id 301,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:47.837100",
    :UUID "1d668d33-5226-4c47-9c3f-463156d47379",
    :speaker nil,
    :transcription "w",
    :elicitor nil,
    :translations
    [{:id 332,
      :transcription "Translocative Prepronominal Prefix",
      :grammaticality ""}]},
   323
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[323 "ANS" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:50.070284",
    :comments
    "Compare CRG (117-118) morpheme /gaa-/ glossed 'ANS' and named 'Animate Nonsingular Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ANS",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "kaa|ANS|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[323 "kaa" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "kaa",
    :id 323,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:50.070284",
    :UUID "01c0d558-4563-4f49-b339-65ae56f499bc",
    :speaker nil,
    :transcription "kaa",
    :elicitor nil,
    :translations
    [{:id 354,
      :transcription "Animate Nonsingular Prepronominal Prefix",
      :grammaticality ""}]},
   306
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[306 "DIST1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:48.416160",
    :comments
    "H3 specification: +H3. TAOC: 27-29, 182. TAOC tag: DIST(i). Compare CRG (109-113, 140, 304-305) morpheme /dee-/ (/doo-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'. Compare BMA 2008 (320-325) morpheme /tee-/ (/too-/) glossed 'DST' and named 'Distributive Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "DIST1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "tee|DIST1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[306 "tee" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "tee",
    :id 306,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:48.416160",
    :UUID "dccb0ae1-e9f4-4274-8169-c6a159ca408d",
    :speaker nil,
    :transcription "tee",
    :elicitor nil,
    :translations
    [{:id 337,
      :transcription "Distributive 1 Prepronominal Prefix",
      :grammaticality ""}]},
   312
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[312 "CISL1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.015006",
    :comments
    "H3 specification: +H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: CISL. Compare CRG (288-291) morpheme /di-/ glossed 'TOW' and named 'Toward Prepronominal Prefix'. Compare CRG (292-293) morpheme /da-/ (/di-/) glossed 'MOT2' and named 'Motion Toward 2 Prepronominal Prefix'. Compare BMA 2008 (326-328) morpheme /ti-/ (/ta-/) glossed 'CIS' and named 'Cislocative Prepronominal Prefix '.",
    :elicitation_method nil,
    :morpheme_gloss "CISL1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ti|CISL1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[312 "ti" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ti",
    :id 312,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.015006",
    :UUID "f311b0b9-8225-4ccb-a312-c9c12ec67933",
    :speaker nil,
    :transcription "ti",
    :elicitor nil,
    :translations
    [{:id 343,
      :transcription "Cislocative 1 Prepronominal Prefix",
      :grammaticality ""}]},
   302
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[302 "PART1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:47.973213",
    :comments
    "H3 specification: ±H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: PART. Compare CRG (283-288) morpheme /ni-/ glossed 'NI' and named 'ni- Prepronominal Prefix '. Compare BMA 2008 (312-317) morpheme /ni-/ glossed 'PRT' and named 'Partitive Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "PART1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ni|PART1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[302 "ni" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ni",
    :id 302,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:47.973213",
    :UUID "bef0b31c-adf7-44ed-bb2f-1c04ca778735",
    :speaker nil,
    :transcription "ni",
    :elicitor nil,
    :translations
    [{:id 333,
      :transcription "Partitive 1 Prepronominal Prefix",
      :grammaticality ""}]},
   324
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[324 "ANS" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:50.172581",
    :comments
    "Compare CRG (117-118) morpheme /gaa-/ glossed 'ANS' and named 'Animate Nonsingular Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ANS",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ka|ANS|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[324 "ka" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ka",
    :id 324,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:50.172581",
    :UUID "a706aba5-8820-46ac-9d82-a807691cc8da",
    :speaker nil,
    :transcription "ka",
    :elicitor nil,
    :translations
    [{:id 355,
      :transcription "Animate Nonsingular Prepronominal Prefix",
      :grammaticality ""}]},
   315
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[315 "CISL2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.311875",
    :comments
    "H3 specification: +H3. tonicity: ±tonic. TAOC: 27-29, 182. TAOC tag: CISL. Compare CRG (289-290) morpheme /da-/ glossed 'TOW2' and named 'Toward 2 Prepronominal Prefix'. Compare CRG (291-293) morpheme /da-/ glossed 'MOT' and named 'Motion Toward Prepronominal Prefix'. Compare CRG (115-117) morpheme /da-/ glossed 'CMF' and named 'Completive Future Prepronominal Prefix '. Compare BMA 2008 (328-329) morpheme /ta-/ glossed 'CSM' and named 'Cislocative Motion Prepronominal Prefix '. Compare BMA 2008 (329-332) morpheme /ta-/ glossed 'FUT' and named 'Future ta- Prepronominal Prefix '.",
    :elicitation_method nil,
    :morpheme_gloss "CISL2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ta|CISL2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[315 "ta" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ta",
    :id 315,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.311875",
    :UUID "3b4296e9-0469-49f7-ade7-89aec29e8eb3",
    :speaker nil,
    :transcription "ta",
    :elicitor nil,
    :translations
    [{:id 346,
      :transcription "Cislocative 2 Prepronominal Prefix",
      :grammaticality ""}]},
   321
   {:date_elicited nil,
    :tags
    [{:id 462, :name "ppp-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[321 "REL" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.873385",
    :comments
    "H3 specification: -H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: REL. Compare CRG (279-282) morpheme /ji-/ glossed 'REL' and named 'Relativizer Prepronominal Prefix'. Compare BMA 2008 (304-305) morpheme /ji-/ glossed 'REL' and named 'Relativizer Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "REL",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "ci|REL|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[321 "ci" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ci",
    :id 321,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.873385",
    :UUID "67b44499-57d7-462e-8906-99b7a5df9b28",
    :speaker nil,
    :transcription "ci",
    :elicitor nil,
    :translations
    [{:id 352,
      :transcription "Relative Prepronominal Prefix",
      :grammaticality ""}]},
   320
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[320 "ITER2" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.784202",
    :comments
    "H3 specification: +H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: ITER. Compare CRG (295) morpheme /vv-/ glossed 'ITR2' and named 'Iterative 2 Prepronominal Prefix'. Compare BMA 2008 (335-336) morpheme /vv-/ glossed 'ITR2' and named 'Iterative 2 Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ITER2",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "vʔ|ITER2|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[320 "vʔ" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "vʔ",
    :id 320,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.784202",
    :UUID "1aaebb3c-838c-4b32-b422-61bea8f12ab5",
    :speaker nil,
    :transcription "vʔ",
    :elicitor nil,
    :translations
    [{:id 351,
      :transcription "Iterative 2 Prepronominal Prefix",
      :grammaticality ""}]},
   318
   {:date_elicited nil,
    :tags
    [{:id 461, :name "ppp-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[318 "ITER1" "PPP"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "PPP",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:49.601962",
    :comments
    "H3 specification: +H3. tonicity: +tonic. TAOC: 27-29, 182. TAOC tag: ITER. Compare CRG (293-296) morpheme /ii-/ (/hii-/) glossed 'ITR' and named 'Iterative Prepronominal Prefix'. Compare BMA 2008 (333-336) morpheme /ii-/ (/hii-/) glossed 'ITR' and named 'Iterative Prepronominal Prefix'.",
    :elicitation_method nil,
    :morpheme_gloss "ITER1",
    :source nil,
    :syntactic_category {:id 103, :name "PPP"},
    :break_gloss_category "iʔ|ITER1|PPP",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[318 "iʔ" "PPP"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "iʔ",
    :id 318,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:49.601962",
    :UUID "ef4c6b41-55bc-4c71-ad90-ead2ca6b4265",
    :speaker nil,
    :transcription "iʔ",
    :elicitor nil,
    :translations
    [{:id 349,
      :transcription "Iterative 1 Prepronominal Prefix",
      :grammaticality ""}]}},
  :mod-sfx-forms
  {343
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[343 "FUT.IMP" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.796522",
    :comments
    "TAOC: 22-23. Compare CRG (81-82) morpheme /-vvʔi/ glossed 'FCM' and named 'Future Command Final Suffix'. Compare BMA 2008 (274-275) morpheme /-vvʔi/ glossed 'FIM' and named 'Future Imperative Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "FUT.IMP",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "vvʔi|FUT.IMP|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[343 "vvʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "vvʔi",
    :id 343,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.796522",
    :UUID "599f2535-39f9-45e0-9a0c-6485e6351573",
    :speaker nil,
    :transcription "vvʔi",
    :elicitor nil,
    :translations
    [{:id 374,
      :transcription "Future Imperative Suffix",
      :grammaticality ""}]},
   329
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[329 "HAB" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.371474",
    :comments
    "TAOC: 22-23. Compare CRG (77-78) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'. Compare BMA 2008 (268-270) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "HAB",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "o|HAB|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[329 "o" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "o",
    :id 329,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.371474",
    :UUID "8a350ddc-022c-4719-9b3b-cc307a34648a",
    :speaker nil,
    :transcription "o",
    :elicitor nil,
    :translations
    [{:id 360, :transcription "Habitual Suffix", :grammaticality ""}]},
   327
   {:date_elicited nil,
    :tags
    [{:id 469, :name "mod-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[327 "HAB" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.189196",
    :comments
    "TAOC: 22-23. Compare CRG (77-78) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'. Compare BMA 2008 (268-270) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "HAB",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "óóʔi|HAB|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[327 "óóʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "óóʔi",
    :id 327,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.189196",
    :UUID "264c30cc-08a4-4d03-9440-fa6a48241f29",
    :speaker nil,
    :transcription "óóʔi",
    :elicitor nil,
    :translations
    [{:id 358, :transcription "Habitual Suffix", :grammaticality ""}]},
   331
   {:date_elicited nil,
    :tags
    [{:id 469, :name "mod-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[331 "ASR" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.577582",
    :comments
    "TAOC: 22-23. Compare CRG (78-79) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'. Compare BMA 2008 (269-270) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "ASR",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "v́v́ʔi|ASR|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[331 "v́v́ʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "v́v́ʔi",
    :id 331,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.577582",
    :UUID "0c0da7aa-1bd3-4b41-8943-465605bf56cd",
    :speaker nil,
    :transcription "v́v́ʔi",
    :elicitor nil,
    :translations
    [{:id 362, :transcription "Assertive Suffix", :grammaticality ""}]},
   341
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[341 "NEG.P" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.583840",
    :comments
    "TAOC: 22-23. Compare CRG (379) morpheme /-v́v́na/ glossed 'NDV' and named 'Negative Deverbalizer Suffix'. Compare BMA 2008 (506) morpheme /-v́v́na/ glossed 'NDV' and named 'Negative Deverbalizer Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "NEG.P",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "vvna|NEG.P|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[341 "vvna" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "vvna",
    :id 341,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.583840",
    :UUID "95b17edc-07d0-4d37-8790-0bcf65d60f5c",
    :speaker nil,
    :transcription "vvna",
    :elicitor nil,
    :translations
    [{:id 372,
      :transcription "Negative Participle Suffix",
      :grammaticality ""}]},
   338
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[338 "FUT.PROG" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.296496",
    :comments
    "TAOC: 22-23. Compare CRG (80-81) morpheme /-éesdi/ glossed 'PFT' and named 'Progressive Future Final Suffix '. Compare BMA 2008 (273-274) morpheme /-éesti/ glossed 'AFT' and named 'Absolute Future Final Suffix '.",
    :elicitation_method nil,
    :morpheme_gloss "FUT.PROG",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "eeʔsti|FUT.PROG|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[338 "eeʔsti" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "eeʔsti",
    :id 338,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.296496",
    :UUID "e6b1eb2b-8bf7-4e64-878a-2305b4f8a232",
    :speaker nil,
    :transcription "eeʔsti",
    :elicitor nil,
    :translations
    [{:id 369,
      :transcription "Future Progressive Suffix",
      :grammaticality ""}]},
   328
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[328 "HAB" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.282039",
    :comments
    "TAOC: 22-23. Compare CRG (77-78) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'. Compare BMA 2008 (268-270) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "HAB",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "ó|HAB|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[328 "ó" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ó",
    :id 328,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.282039",
    :UUID "d919f54b-1fdb-4624-bebb-340555a5d1c4",
    :speaker nil,
    :transcription "ó",
    :elicitor nil,
    :translations
    [{:id 359, :transcription "Habitual Suffix", :grammaticality ""}]},
   334
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[334 "REP" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.906279",
    :comments
    "TAOC: 22-23. Compare CRG (79-80) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'. Compare BMA 2008 (270-273) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "REP",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "éʔi|REP|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[334 "éʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "éʔi",
    :id 334,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.906279",
    :UUID "a9ceede5-31d1-4ac5-92b8-7a763f04d566",
    :speaker nil,
    :transcription "éʔi",
    :elicitor nil,
    :translations
    [{:id 365, :transcription "Reportive Suffix", :grammaticality ""}]},
   325
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[325 "IND" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:51.966902",
    :comments "TAOC: 22-23.",
    :elicitation_method nil,
    :morpheme_gloss "IND",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "a|IND|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[325 "a" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "a",
    :id 325,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:51.966902",
    :UUID "4d217986-b077-42b9-bb8e-53faa7b90499",
    :speaker nil,
    :transcription "a",
    :elicitor nil,
    :translations
    [{:id 356, :transcription "Indicative Suffix", :grammaticality ""}]},
   340
   {:date_elicited nil,
    :tags
    [{:id 469, :name "mod-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[340 "MOT" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.478121",
    :comments
    "TAOC: 22-23. Compare CRG (82, 115-117) morpheme /-i/ (/-is-/) glossed 'CMF' and named 'Completive Future Final Suffix'. Compare BMA 2008 (329-332) morpheme /-i/ (/-is-/) glossed 'MOT' and named 'Motion Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "MOT",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "is|MOT|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[340 "is" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "is",
    :id 340,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.478121",
    :UUID "14930403-3c8b-4604-9b92-0ab363d47578",
    :speaker nil,
    :transcription "is",
    :elicitor nil,
    :translations
    [{:id 371, :transcription "Motion Suffix", :grammaticality ""}]},
   332
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[332 "ASR" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.708956",
    :comments
    "TAOC: 22-23. Compare CRG (78-79) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'. Compare BMA 2008 (269-270) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "ASR",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "v́|ASR|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[332 "v́" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "v́",
    :id 332,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.708956",
    :UUID "310680ba-7d54-42a9-911c-b1509fcaa3f3",
    :speaker nil,
    :transcription "v́",
    :elicitor nil,
    :translations
    [{:id 363, :transcription "Assertive Suffix", :grammaticality ""}]},
   330
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[330 "ASR" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.465256",
    :comments
    "TAOC: 22-23. Compare CRG (78-79) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'. Compare BMA 2008 (269-270) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "ASR",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "vv́ʔi|ASR|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[330 "vv́ʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "vv́ʔi",
    :id 330,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.465256",
    :UUID "1eb7fbba-75bd-4e39-9c74-47b5b09f9da3",
    :speaker nil,
    :transcription "vv́ʔi",
    :elicitor nil,
    :translations
    [{:id 361, :transcription "Assertive Suffix", :grammaticality ""}]},
   342
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[342 "NOM" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.673222",
    :comments "TAOC: 22-23.",
    :elicitation_method nil,
    :morpheme_gloss "NOM",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "i|NOM|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[342 "i" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "i",
    :id 342,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.673222",
    :UUID "f0a91aa2-ce77-4c8c-83db-8058d764ee60",
    :speaker nil,
    :transcription "i",
    :elicitor nil,
    :translations
    [{:id 373, :transcription "Nominal Suffix", :grammaticality ""}]},
   335
   {:date_elicited nil,
    :tags
    [{:id 469, :name "mod-pre-vocalic"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[335 "REP" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.997899",
    :comments
    "TAOC: 22-23. Compare CRG (79-80) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'. Compare BMA 2008 (270-273) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "REP",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "ééʔi|REP|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[335 "ééʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "ééʔi",
    :id 335,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.997899",
    :UUID "9869dc71-3e24-420f-a922-5313d2da9207",
    :speaker nil,
    :transcription "ééʔi",
    :elicitor nil,
    :translations
    [{:id 366, :transcription "Reportive Suffix", :grammaticality ""}]},
   339
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[339 "MOT" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.387542",
    :comments
    "TAOC: 22-23. Compare CRG (82, 115-117) morpheme /-i/ (/-is-/) glossed 'CMF' and named 'Completive Future Final Suffix'. Compare BMA 2008 (329-332) morpheme /-i/ (/-is-/) glossed 'MOT' and named 'Motion Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "MOT",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "i|MOT|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[339 "i" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "i",
    :id 339,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.387542",
    :UUID "627ad5d2-839e-48dd-a586-5d8a88fff0f1",
    :speaker nil,
    :transcription "i",
    :elicitor nil,
    :translations
    [{:id 370, :transcription "Motion Suffix", :grammaticality ""}]},
   337
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[337 "REP" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.211599",
    :comments
    "TAOC: 22-23. Compare CRG (79-80) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'. Compare BMA 2008 (270-273) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "REP",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "e|REP|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[337 "e" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "e",
    :id 337,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.211599",
    :UUID "effc9d04-0d6f-4214-8674-4df14fc664ff",
    :speaker nil,
    :transcription "e",
    :elicitor nil,
    :translations
    [{:id 368, :transcription "Reportive Suffix", :grammaticality ""}]},
   333
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[333 "ASR" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.820351",
    :comments
    "TAOC: 22-23. Compare CRG (78-79) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'. Compare BMA 2008 (269-270) morpheme /-vv́ʔi/ (/-v/) glossed 'EXP' and named 'Experienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "ASR",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "v|ASR|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[333 "v" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "v",
    :id 333,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.820351",
    :UUID "cf8a8195-8c02-48fd-a313-2e4f61a5724e",
    :speaker nil,
    :transcription "v",
    :elicitor nil,
    :translations
    [{:id 364, :transcription "Assertive Suffix", :grammaticality ""}]},
   326
   {:date_elicited nil,
    :tags
    [{:id 468, :name "mod-pre-consonantal"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[326 "HAB" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:52.076958",
    :comments
    "TAOC: 22-23. Compare CRG (77-78) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'. Compare BMA 2008 (268-270) morpheme /-óʔi/ (/-o/) glossed 'HAB' and named 'Habitual Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "HAB",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "óʔi|HAB|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[326 "óʔi" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "óʔi",
    :id 326,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:52.076958",
    :UUID "0758d31b-bd9f-45b5-aa5e-36f815cb1ad5",
    :speaker nil,
    :transcription "óʔi",
    :elicitor nil,
    :translations
    [{:id 357, :transcription "Habitual Suffix", :grammaticality ""}]},
   336
   {:date_elicited nil,
    :tags
    [{:id 470, :name "mod-pre-v"}
     {:id 457, :name "ingest-uchihara-root:2019-02-27T19:12:42.832Z"}],
    :morpheme_break_ids [[[[336 "REP" "MOD"]]]],
    :verifier nil,
    :modifier
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :narrow_phonetic_transcription "",
    :syntactic_category_string "MOD",
    :semantics "",
    :enterer
    {:id 1, :first_name "Admin", :last_name "Admin", :role "administrator"},
    :datetime_modified "2019-02-27T19:12:53.120126",
    :comments
    "TAOC: 22-23. Compare CRG (79-80) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'. Compare BMA 2008 (270-273) morpheme /-eeʔi/ (/-e/) glossed 'NXP' and named 'Nonexperienced Past Final Suffix'.",
    :elicitation_method nil,
    :morpheme_gloss "REP",
    :source nil,
    :syntactic_category {:id 105, :name "MOD"},
    :break_gloss_category "é|REP|MOD",
    :grammaticality "",
    :speaker_comments "",
    :morpheme_gloss_ids [[[[336 "é" "MOD"]]]],
    :status "tested",
    :syntax "",
    :morpheme_break "é",
    :id 336,
    :phonetic_transcription "",
    :files [],
    :datetime_entered "2019-02-27T19:12:53.120126",
    :UUID "c84839df-9c7c-423d-a430-95c21d5937cd",
    :speaker nil,
    :transcription "é",
    :elicitor nil,
    :translations
    [{:id 367, :transcription "Reportive Suffix", :grammaticality ""}]}}})

(comment

  (+ 2 3)

  (fetch-upload-asp-sfx-forms (get-fake-state))

  (-> (fetch-upload-asp-sfx-forms (get-fake-state))
      first
      keys)

  (fetch-upload-asp-sfx-forms (get-fake-state) :disable-cache false)

  (-> (fetch-upload-asp-sfx-forms (get-fake-state))
      first
      count)

  (asp-table->sec-of-maps (get-fake-state) tmp)

  (take 10 (repeat [1 2]))

)
