(ns dailp-ingest-clj.orthographies-test)

(def extracted-orthographies
 [{:segment "short low (L)",
  :Uchihara-database "a",
  :Feeling-1975 "ạ²",
  :TAOC "a",
  :CRG "a",
  :TAOC-modified-community "a",
  :Cherokee-Tone-Project "ā",
  :Cherokee-Narratives "a̱",
  :DAILP "a"}
 {:segment "short high (H)",
  :Uchihara-database "a!",
  :Feeling-1975 "ạ³",
  :TAOC "á",
  :CRG "á",
  :TAOC-modified-community "á",
  :Cherokee-Tone-Project "á",
  :Cherokee-Narratives "a̱³",
  :DAILP "á"}
 {:segment "short lowfall",
  :Uchihara-database "a`",
  :Feeling-1975 "ạ¹",
  :TAOC "à",
  :CRG "à",
  :TAOC-modified-community "à",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "à"}
 {:segment "short superhigh",
  :Uchihara-database "a\" ",
  :Feeling-1975 "ạ⁴",
  :TAOC "a̋",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "a̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "a:",
  :Feeling-1975 "a²",
  :TAOC "aa",
  :CRG "aa",
  :TAOC-modified-community "a:",
  :Cherokee-Tone-Project "ā:",
  :Cherokee-Narratives "a",
  :DAILP "aa"}
 {:segment "long high (HH)",
  :Uchihara-database "a:!",
  :Feeling-1975 "a³",
  :TAOC "áá",
  :CRG "áa",
  :TAOC-modified-community "á:",
  :Cherokee-Tone-Project "á:",
  :Cherokee-Narratives "a³",
  :DAILP "áá"}
 {:segment "rising (LH)",
  :Uchihara-database "a:*",
  :Feeling-1975 "a²³",
  :TAOC "aá",
  :CRG "aá",
  :TAOC-modified-community "ǎ:",
  :Cherokee-Tone-Project "ǎ:",
  :Cherokee-Narratives "a²³",
  :DAILP "aá"}
 {:segment "falling (HL)",
  :Uchihara-database "a:^",
  :Feeling-1975 "a³²",
  :TAOC "áa",
  :CRG "áà",
  :TAOC-modified-community "â:",
  :Cherokee-Tone-Project "â:",
  :Cherokee-Narratives "a³²",
  :DAILP "áa"}
 {:segment "lowfall (LF)",
  :Uchihara-database "a:`",
  :Feeling-1975 "a¹",
  :TAOC "àà",
  :CRG "aà",
  :TAOC-modified-community "à:",
  :Cherokee-Tone-Project "à:",
  :Cherokee-Narratives "a¹",
  :DAILP "àà"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "a:\" ",
  :Feeling-1975 "a⁴",
  :TAOC "aa̋",
  :CRG "áá",
  :TAOC-modified-community "a̋:",
  :Cherokee-Tone-Project "a̋:",
  :Cherokee-Narratives "a⁴",
  :DAILP "aa̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "short low (L)",
  :Uchihara-database "e",
  :Feeling-1975 "ẹ²",
  :TAOC "e",
  :CRG "e",
  :TAOC-modified-community "e",
  :Cherokee-Tone-Project "ē",
  :Cherokee-Narratives "e̱",
  :DAILP "e"}
 {:segment "short high (H)",
  :Uchihara-database "e!",
  :Feeling-1975 "ẹ³",
  :TAOC "é",
  :CRG "é",
  :TAOC-modified-community "é",
  :Cherokee-Tone-Project "é",
  :Cherokee-Narratives "e̱³",
  :DAILP "é"}
 {:segment "short lowfall",
  :Uchihara-database "e`",
  :Feeling-1975 "ẹ¹",
  :TAOC "è",
  :CRG "è",
  :TAOC-modified-community "è",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "è"}
 {:segment "short superhigh",
  :Uchihara-database "e\" ",
  :Feeling-1975 "ẹ⁴",
  :TAOC "e̋",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "e̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "e:",
  :Feeling-1975 "e²",
  :TAOC "ee",
  :CRG "ee",
  :TAOC-modified-community "e:",
  :Cherokee-Tone-Project "ē:",
  :Cherokee-Narratives "e",
  :DAILP "ee"}
 {:segment "long high (HH)",
  :Uchihara-database "e:!",
  :Feeling-1975 "e³",
  :TAOC "éé",
  :CRG "ée",
  :TAOC-modified-community "é:",
  :Cherokee-Tone-Project "é:",
  :Cherokee-Narratives "e³",
  :DAILP "éé"}
 {:segment "rising (LH)",
  :Uchihara-database "e:*",
  :Feeling-1975 "e²³",
  :TAOC "eé",
  :CRG "eé",
  :TAOC-modified-community "ě:",
  :Cherokee-Tone-Project "ě:",
  :Cherokee-Narratives "e²³",
  :DAILP "eé"}
 {:segment "falling (HL)",
  :Uchihara-database "e:^",
  :Feeling-1975 "e³²",
  :TAOC "ée",
  :CRG "éè",
  :TAOC-modified-community "ê:",
  :Cherokee-Tone-Project "ê:",
  :Cherokee-Narratives "e³²",
  :DAILP "ée"}
 {:segment "lowfall (LF)",
  :Uchihara-database "e:`",
  :Feeling-1975 "e¹",
  :TAOC "èè",
  :CRG "eè",
  :TAOC-modified-community "è:",
  :Cherokee-Tone-Project "è:",
  :Cherokee-Narratives "e¹",
  :DAILP "èè"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "e:\" ",
  :Feeling-1975 "e⁴",
  :TAOC "ee̋",
  :CRG "éé",
  :TAOC-modified-community "e̋:",
  :Cherokee-Tone-Project "e̋:",
  :Cherokee-Narratives "e⁴",
  :DAILP "ee̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "short low (L)",
  :Uchihara-database "i",
  :Feeling-1975 "ị²",
  :TAOC "i",
  :CRG "i",
  :TAOC-modified-community "i",
  :Cherokee-Tone-Project " ī",
  :Cherokee-Narratives "i̱",
  :DAILP "i"}
 {:segment "short high (H)",
  :Uchihara-database "i!",
  :Feeling-1975 "ị³",
  :TAOC "í",
  :CRG "í",
  :TAOC-modified-community "í",
  :Cherokee-Tone-Project "í",
  :Cherokee-Narratives "i̱³",
  :DAILP "í"}
 {:segment "short lowfall",
  :Uchihara-database "i`",
  :Feeling-1975 "ị¹",
  :TAOC "ì",
  :CRG "ì",
  :TAOC-modified-community "ì",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "ì"}
 {:segment "short superhigh",
  :Uchihara-database "i\" ",
  :Feeling-1975 "ị⁴",
  :TAOC "i̋",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "i̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "i:",
  :Feeling-1975 "i²",
  :TAOC "ii",
  :CRG "ii",
  :TAOC-modified-community "i:",
  :Cherokee-Tone-Project " ī:",
  :Cherokee-Narratives "i",
  :DAILP "ii"}
 {:segment "long high (HH)",
  :Uchihara-database "i:!",
  :Feeling-1975 "i³",
  :TAOC "íí",
  :CRG "íi",
  :TAOC-modified-community "í:",
  :Cherokee-Tone-Project "í:",
  :Cherokee-Narratives "i³",
  :DAILP "íí"}
 {:segment "rising (LH)",
  :Uchihara-database "i:*",
  :Feeling-1975 "i²³",
  :TAOC "ií",
  :CRG "ií",
  :TAOC-modified-community "ǐ:",
  :Cherokee-Tone-Project "ǐ:",
  :Cherokee-Narratives "i²³",
  :DAILP "ií"}
 {:segment "falling (HL)",
  :Uchihara-database "i:^",
  :Feeling-1975 "i³²",
  :TAOC "íi",
  :CRG "íì",
  :TAOC-modified-community "î:",
  :Cherokee-Tone-Project "î:",
  :Cherokee-Narratives "i³²",
  :DAILP "íi"}
 {:segment "lowfall (LF)",
  :Uchihara-database "i:`",
  :Feeling-1975 "i¹",
  :TAOC "ìì",
  :CRG "iì",
  :TAOC-modified-community "ì:",
  :Cherokee-Tone-Project "ì:",
  :Cherokee-Narratives "i¹",
  :DAILP "ìì"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "i:\" ",
  :Feeling-1975 "i⁴",
  :TAOC "ii̋",
  :CRG "íí",
  :TAOC-modified-community "i̋:",
  :Cherokee-Tone-Project "i̋:",
  :Cherokee-Narratives "i⁴",
  :DAILP "ii̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "short low (L)",
  :Uchihara-database "o",
  :Feeling-1975 "ọ²",
  :TAOC "o",
  :CRG "o",
  :TAOC-modified-community "o",
  :Cherokee-Tone-Project "ō",
  :Cherokee-Narratives "o̱",
  :DAILP "o"}
 {:segment "short high (H)",
  :Uchihara-database "o!",
  :Feeling-1975 "ọ³",
  :TAOC "ó",
  :CRG "ó",
  :TAOC-modified-community "ó",
  :Cherokee-Tone-Project "ó",
  :Cherokee-Narratives "o̱³",
  :DAILP "ó"}
 {:segment "short lowfall",
  :Uchihara-database "o`",
  :Feeling-1975 "ọ¹",
  :TAOC "ò",
  :CRG "ò",
  :TAOC-modified-community "ò",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "ò"}
 {:segment "short superhigh",
  :Uchihara-database "o\" ",
  :Feeling-1975 "ọ⁴",
  :TAOC "ő",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "ő"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "o:",
  :Feeling-1975 "o²",
  :TAOC "oo",
  :CRG "oo",
  :TAOC-modified-community "o:",
  :Cherokee-Tone-Project "ō:",
  :Cherokee-Narratives "o",
  :DAILP "oo"}
 {:segment "long high (HH)",
  :Uchihara-database "o:!",
  :Feeling-1975 "o³",
  :TAOC "óó",
  :CRG "óo",
  :TAOC-modified-community "ó:",
  :Cherokee-Tone-Project "ó:",
  :Cherokee-Narratives "o³",
  :DAILP "óó"}
 {:segment "rising (LH)",
  :Uchihara-database "o:*",
  :Feeling-1975 "o²³",
  :TAOC "oó",
  :CRG "oó",
  :TAOC-modified-community "ǒ:",
  :Cherokee-Tone-Project "ǒ:",
  :Cherokee-Narratives "o²³",
  :DAILP "oó"}
 {:segment "falling (HL)",
  :Uchihara-database "o:^",
  :Feeling-1975 "o³²",
  :TAOC "óo",
  :CRG "óò",
  :TAOC-modified-community "ô",
  :Cherokee-Tone-Project "ô",
  :Cherokee-Narratives "o³²",
  :DAILP "óo"}
 {:segment "lowfall (LF)",
  :Uchihara-database "o:`",
  :Feeling-1975 "o¹",
  :TAOC "òò",
  :CRG "oò",
  :TAOC-modified-community "ò:",
  :Cherokee-Tone-Project "ò:",
  :Cherokee-Narratives "o¹",
  :DAILP "òò"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "o:\" ",
  :Feeling-1975 "o⁴",
  :TAOC "oő",
  :CRG "óó",
  :TAOC-modified-community "ő:",
  :Cherokee-Tone-Project "ő:",
  :Cherokee-Narratives "o⁴",
  :DAILP "oő"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "short low (L)",
  :Uchihara-database "u",
  :Feeling-1975 "ụ²",
  :TAOC "u",
  :CRG "u",
  :TAOC-modified-community "u",
  :Cherokee-Tone-Project " ū",
  :Cherokee-Narratives "u̱",
  :DAILP "u"}
 {:segment "short high (H)",
  :Uchihara-database "u!",
  :Feeling-1975 "ụ³",
  :TAOC "ú",
  :CRG "ú",
  :TAOC-modified-community "ú",
  :Cherokee-Tone-Project "ú",
  :Cherokee-Narratives "u̱³",
  :DAILP "ú"}
 {:segment "short lowfall",
  :Uchihara-database "u`",
  :Feeling-1975 "ụ¹",
  :TAOC "ù",
  :CRG "ù",
  :TAOC-modified-community "ù",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "ù"}
 {:segment "short superhigh",
  :Uchihara-database "u\" ",
  :Feeling-1975 "ụ⁴",
  :TAOC "ű",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "ű"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "u:",
  :Feeling-1975 "u²",
  :TAOC "uu",
  :CRG "uu",
  :TAOC-modified-community "u:",
  :Cherokee-Tone-Project " ū:",
  :Cherokee-Narratives "u",
  :DAILP "uu"}
 {:segment "long high (HH)",
  :Uchihara-database "u:!",
  :Feeling-1975 "u³",
  :TAOC "úú",
  :CRG "úu",
  :TAOC-modified-community "ú:",
  :Cherokee-Tone-Project "ú:",
  :Cherokee-Narratives "u³",
  :DAILP "úú"}
 {:segment "rising (LH)",
  :Uchihara-database "u:*",
  :Feeling-1975 "u²³",
  :TAOC "uú",
  :CRG "uú",
  :TAOC-modified-community "ǔ",
  :Cherokee-Tone-Project "ǔ",
  :Cherokee-Narratives "u²³",
  :DAILP "uú"}
 {:segment "falling (HL)",
  :Uchihara-database "u:^",
  :Feeling-1975 "u³²",
  :TAOC "úu",
  :CRG "úù",
  :TAOC-modified-community "û:",
  :Cherokee-Tone-Project "û:",
  :Cherokee-Narratives "u³²",
  :DAILP "úu"}
 {:segment "lowfall (LF)",
  :Uchihara-database "u:`",
  :Feeling-1975 "u¹",
  :TAOC "ùù",
  :CRG "uù",
  :TAOC-modified-community "ù:",
  :Cherokee-Tone-Project "ù:",
  :Cherokee-Narratives "u¹",
  :DAILP "ùù"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "u:\" ",
  :Feeling-1975 "u⁴",
  :TAOC "uű",
  :CRG "úú",
  :TAOC-modified-community "ű:",
  :Cherokee-Tone-Project "ű:",
  :Cherokee-Narratives "u⁴",
  :DAILP "uű"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "short low (L)",
  :Uchihara-database "v",
  :Feeling-1975 "ṿ²",
  :TAOC "v",
  :CRG "v",
  :TAOC-modified-community "v",
  :Cherokee-Tone-Project " v̄",
  :Cherokee-Narratives "v̱",
  :DAILP "v"}
 {:segment "short high (H)",
  :Uchihara-database "v!",
  :Feeling-1975 "ṿ³",
  :TAOC "v́",
  :CRG "v́",
  :TAOC-modified-community "v́",
  :Cherokee-Tone-Project "v́",
  :Cherokee-Narratives "v̱³",
  :DAILP "v́"}
 {:segment "short lowfall",
  :Uchihara-database "v`",
  :Feeling-1975 "ṿ¹",
  :TAOC "v̀",
  :CRG "v̀",
  :TAOC-modified-community "v̀",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "v̀"}
 {:segment "short superhigh",
  :Uchihara-database "v\" ",
  :Feeling-1975 "ṿ⁴",
  :TAOC "v̋",
  :CRG "?",
  :TAOC-modified-community "?",
  :Cherokee-Tone-Project "?",
  :Cherokee-Narratives "?",
  :DAILP "v̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "long low (LL)",
  :Uchihara-database "v:",
  :Feeling-1975 "v²",
  :TAOC "vv",
  :CRG "vv",
  :TAOC-modified-community "v:",
  :Cherokee-Tone-Project " v̄:",
  :Cherokee-Narratives "v",
  :DAILP "vv"}
 {:segment "long high (HH)",
  :Uchihara-database "v:!",
  :Feeling-1975 "v³",
  :TAOC "v́v́",
  :CRG "v́v",
  :TAOC-modified-community "v́:",
  :Cherokee-Tone-Project "v́:",
  :Cherokee-Narratives "v³",
  :DAILP "v́v́"}
 {:segment "rising (LH)",
  :Uchihara-database "v:*",
  :Feeling-1975 "v²³",
  :TAOC "vv́",
  :CRG "vv́",
  :TAOC-modified-community "v̌:",
  :Cherokee-Tone-Project "v̌:",
  :Cherokee-Narratives "v²³",
  :DAILP "vv́"}
 {:segment "falling (HL)",
  :Uchihara-database "v:^",
  :Feeling-1975 "v³²",
  :TAOC "v́v",
  :CRG "v́v̀",
  :TAOC-modified-community "v̂:",
  :Cherokee-Tone-Project "v̂:",
  :Cherokee-Narratives "v³²",
  :DAILP "v́v"}
 {:segment "lowfall (LF)",
  :Uchihara-database "v:`",
  :Feeling-1975 "v¹",
  :TAOC "v̀v̀",
  :CRG "vv̀",
  :TAOC-modified-community "v̀:",
  :Cherokee-Tone-Project "v̀:",
  :Cherokee-Narratives "v¹",
  :DAILP "v̀v̀"}
 {:segment "superhigh (SH) \n= highfall ",
  :Uchihara-database "v:\" ",
  :Feeling-1975 "v⁴",
  :TAOC "vv̋",
  :CRG "v́v́",
  :TAOC-modified-community "v̋:",
  :Cherokee-Tone-Project "v̋:",
  :Cherokee-Narratives "v⁴",
  :DAILP "vv̋"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "any vowel",
  :Uchihara-database "V",
  :Feeling-1975 "V",
  :TAOC "V",
  :CRG "V",
  :TAOC-modified-community "V",
  :Cherokee-Tone-Project "V",
  :Cherokee-Narratives "V",
  :DAILP "V"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "unaspirated alveolar stop",
  :Uchihara-database "d",
  :Feeling-1975 "d",
  :TAOC "t",
  :CRG "d",
  :TAOC-modified-community "d",
  :Cherokee-Tone-Project "d",
  :Cherokee-Narratives "d",
  :DAILP "d"}
 {:segment "aspirated alveolar stop",
  :Uchihara-database "t",
  :Feeling-1975 "t",
  :TAOC "th ",
  :CRG "t",
  :TAOC-modified-community "t",
  :Cherokee-Tone-Project "t",
  :Cherokee-Narratives "t",
  :DAILP "t"}
 {:segment "unaspirated velar stop",
  :Uchihara-database "g",
  :Feeling-1975 "g",
  :TAOC "k",
  :CRG "g",
  :TAOC-modified-community "g",
  :Cherokee-Tone-Project "g",
  :Cherokee-Narratives "g",
  :DAILP "g"}
 {:segment "aspirated velar stop",
  :Uchihara-database "k",
  :Feeling-1975 "k",
  :TAOC "kh ",
  :CRG "k",
  :TAOC-modified-community "k",
  :Cherokee-Tone-Project "k",
  :Cherokee-Narratives "k",
  :DAILP "k"}
 {:segment "unaspirated labiovelar stop",
  :Uchihara-database "gw",
  :Feeling-1975 "gw",
  :TAOC "kw",
  :CRG "gw",
  :TAOC-modified-community "gw",
  :Cherokee-Tone-Project "gw",
  :Cherokee-Narratives "gw",
  :DAILP "gw"}
 {:segment "aspirated labiovelar stop",
  :Uchihara-database "kw",
  :Feeling-1975 "kw",
  :TAOC "kwh",
  :CRG "kw",
  :TAOC-modified-community "kw",
  :Cherokee-Tone-Project "kw",
  :Cherokee-Narratives "kw",
  :DAILP "kw"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "unaspirated alveolar affricate",
  :Uchihara-database "j",
  :Feeling-1975 "j",
  :TAOC "c ",
  :CRG "j",
  :TAOC-modified-community "j",
  :Cherokee-Tone-Project "j",
  :Cherokee-Narratives "j",
  :DAILP "j"}
 {:segment "aspirated alveolar affricate",
  :Uchihara-database "ch",
  :Feeling-1975 "ch",
  :TAOC "ch",
  :CRG "ch",
  :TAOC-modified-community "ch",
  :Cherokee-Tone-Project "ch",
  :Cherokee-Narratives "ch",
  :DAILP "ch"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "lateral alveolar affricate",
  :Uchihara-database "dl",
  :Feeling-1975 "dl",
  :TAOC "tl",
  :CRG "dl",
  :TAOC-modified-community "dl",
  :Cherokee-Tone-Project "dl",
  :Cherokee-Narratives "dl",
  :DAILP "dl"}
 {:segment "voiceless alveolar affricate",
  :Uchihara-database "tl",
  :Feeling-1975 "tl",
  :TAOC "tlh",
  :CRG "tl",
  :TAOC-modified-community "tl",
  :Cherokee-Tone-Project "tl",
  :Cherokee-Narratives "tl",
  :DAILP "tl"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "alveolar fricative",
  :Uchihara-database "s",
  :Feeling-1975 "s",
  :TAOC "s",
  :CRG "s",
  :TAOC-modified-community "s",
  :Cherokee-Tone-Project "s",
  :Cherokee-Narratives "s",
  :DAILP "s"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "glottal fricative",
  :Uchihara-database "h",
  :Feeling-1975 "h",
  :TAOC "h",
  :CRG "h",
  :TAOC-modified-community "h",
  :Cherokee-Tone-Project "h",
  :Cherokee-Narratives "h",
  :DAILP "h"}
 {:segment "glottal stop",
  :Uchihara-database "'",
  :Feeling-1975 "ʔ",
  :TAOC "ʔ",
  :CRG "ʔ",
  :TAOC-modified-community "ʔ",
  :Cherokee-Tone-Project "ʔ",
  :Cherokee-Narratives "ʔ",
  :DAILP "ʔ"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "alveolar liquid",
  :Uchihara-database "l",
  :Feeling-1975 "l",
  :TAOC "l",
  :CRG "l",
  :TAOC-modified-community "l",
  :Cherokee-Tone-Project "l",
  :Cherokee-Narratives "l",
  :DAILP "l"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "palatal glide",
  :Uchihara-database "y",
  :Feeling-1975 "y",
  :TAOC "y",
  :CRG "y",
  :TAOC-modified-community "y",
  :Cherokee-Tone-Project "y",
  :Cherokee-Narratives "y",
  :DAILP "y"}
 {:segment "labiovelar glide",
  :Uchihara-database "w",
  :Feeling-1975 "w",
  :TAOC "w",
  :CRG "w",
  :TAOC-modified-community "w",
  :Cherokee-Tone-Project "w",
  :Cherokee-Narratives "w",
  :DAILP "w"}
 {:segment "",
  :Uchihara-database "",
  :Feeling-1975 "",
  :TAOC "",
  :CRG "",
  :TAOC-modified-community "",
  :Cherokee-Tone-Project "",
  :Cherokee-Narratives "",
  :DAILP ""}
 {:segment "bilabial nasal",
  :Uchihara-database "m",
  :Feeling-1975 "m",
  :TAOC "m",
  :CRG "m",
  :TAOC-modified-community "m",
  :Cherokee-Tone-Project "m",
  :Cherokee-Narratives "m",
  :DAILP "m"}])
